# Generated by Django 4.2.3 on 2023-07-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0003_remove_signature_message_signature_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Desaprobado', 'Desaprobado')], default='Pendiente', max_length=20),
        ),
    ]
