# Generated by Django 4.2.3 on 2023-07-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0004_signature_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Desaprobado', 'Desaprobado')], default='Pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
